# Generated by Django 4.2.20 on 2025-04-03 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プッシュ通知ログ',
                'verbose_name_plural': 'プッシュ通知ログ',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_reminders', models.BooleanField(default=True)),
                ('new_articles', models.BooleanField(default=True)),
                ('system_notices', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プッシュ通知サブスクリプション',
                'verbose_name_plural': 'プッシュ通知サブスクリプション',
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
