# タスクに関する定数
TASK_STATUS_TODO = 0
TASK_STATUS_IN_PROGRESS = 1
TASK_STATUS_COMPLETED = 2

TASK_STATUS_CHOICES = [
    (TASK_STATUS_TODO, "未着手"),
    (TASK_STATUS_IN_PROGRESS, "進行中"),
    (TASK_STATUS_COMPLETED, "完了"),
]

TASK_PRIORITY_LOW = 0
TASK_PRIORITY_MEDIUM = 1
TASK_PRIORITY_HIGH = 2

TASK_PRIORITY_CHOICES = [
    (TASK_PRIORITY_LOW, "低"),
    (TASK_PRIORITY_MEDIUM, "中"),
    (TASK_PRIORITY_HIGH, "高"),
]
