# Generated by Django 4.2.19 on 2025-03-01 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('description', models.CharField(max_length=300, verbose_name='詳細')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='締め切り')),
                ('priority', models.SmallIntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], default=1, verbose_name='優先度')),
                ('status', models.SmallIntegerField(choices=[(0, '未着手'), (1, '進行中'), (2, '完了')], default=0, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='academics.lecture', verbose_name='講義')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'タスク',
            },
        ),
    ]
