# Generated by Django 4.2.19 on 2025-03-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_schedule_id'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='lecture',
        ),
        migrations.AddField(
            model_name='task',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='academics.registration', verbose_name='講義'),
        ),
    ]
