# Generated by Django 4.2.19 on 2025-03-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_schedule_id'),
        ('tasks', '0002_remove_task_lecture_task_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='academics.registration', verbose_name='講義'),
        ),
    ]
