# Generated by Django 4.2.20 on 2025-03-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='詳細'),
        ),
    ]
