# Generated by Django 4.2.19 on 2025-03-01 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('number', models.PositiveSmallIntegerField(choices=[(1, '第1ターム(春)'), (2, '第2ターム(夏)'), (3, '第3ターム(秋)'), (4, '第4ターム(冬)')], primary_key=True, serialize=False, verbose_name='ターム')),
            ],
            options={
                'verbose_name': 'ターム',
                'verbose_name_plural': '学期',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日'), (7, '日曜日')], verbose_name='曜日')),
                ('time', models.PositiveSmallIntegerField(choices=[(1, '1限'), (2, '2限'), (3, '3限'), (4, '4限'), (5, '5限')], verbose_name='時限')),
            ],
            options={
                'verbose_name': 'スケジュール',
                'verbose_name_plural': 'スケジュール',
                'unique_together': {('day', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, verbose_name='講義コード')),
                ('syllabus_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='シラバスコード')),
                ('name', models.CharField(max_length=200, verbose_name='講義名')),
                ('grade', models.IntegerField(default=1, verbose_name='対象学年')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='講義室')),
                ('instructor', models.CharField(max_length=200, verbose_name='担当教員')),
                ('units', models.FloatField(default=0, verbose_name='単位数')),
                ('is_required', models.BooleanField(default=False, verbose_name='必修')),
                ('is_exam', models.BooleanField(default=False, verbose_name='期末テスト')),
                ('description', models.CharField(blank=True, max_length=5000, verbose_name='概要')),
                ('eval_method', models.CharField(blank=True, max_length=1000, verbose_name='評価方法')),
                ('biko', models.CharField(blank=True, max_length=300, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('departments', models.ManyToManyField(related_name='lectures', to='accounts.department', verbose_name='履修可能学科')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('schedules', models.ManyToManyField(related_name='lectures', to='academics.schedule', verbose_name='スケジュール')),
                ('terms', models.ManyToManyField(related_name='lectures', to='academics.term', verbose_name='ターム')),
            ],
            options={
                'verbose_name_plural': '講義',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='年度')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academics.lecture', verbose_name='講義')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '登録状況',
                'unique_together': {('user', 'lecture', 'year')},
            },
        ),
    ]
