# Generated by Django 4.2.19 on 2025-03-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
