# Generated by Django 4.2.19 on 2025-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_schedule_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='シラバスID')),
                ('name', models.CharField(max_length=200, verbose_name='講義名')),
                ('units', models.FloatField(default=0, verbose_name='単位数')),
                ('instructor', models.CharField(max_length=200, verbose_name='担当教員')),
                ('grade', models.IntegerField(default=1, verbose_name='対象学年')),
                ('type', models.CharField(verbose_name='講義形態')),
                ('purpose', models.TextField(verbose_name='講義の目的')),
                ('goal', models.TextField(blank=True, verbose_name='到達目標')),
                ('requirements', models.CharField(blank=True, verbose_name='受講要件')),
                ('is_required', models.BooleanField(default=False, verbose_name='必修')),
                ('is_exam', models.BooleanField(default=False, verbose_name='期末テスト')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='概要')),
                ('eval_method', models.TextField(blank=True, max_length=1000, verbose_name='評価方法')),
                ('textbook', models.TextField(blank=True, verbose_name='教科書等')),
                ('feedback', models.TextField(blank=True, verbose_name='課題や試験に対するフィードバック')),
                ('schedules', models.ManyToManyField(blank=True, null=True, related_name='syllabuses', to='academics.schedule', verbose_name='スケジュール')),
                ('terms', models.ManyToManyField(related_name='syllabuses', to='academics.term', verbose_name='ターム')),
            ],
        ),
    ]
