# Generated by Django 4.2.19 on 2025-03-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_syllabus_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='syllabuses', to='academics.schedule', verbose_name='スケジュール'),
        ),
    ]
