# Generated by Django 4.2.19 on 2025-03-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_syllabus_schedules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name_plural': 'シラバス'},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='eval_method',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='is_exam',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='syllabus_id',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='units',
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecture',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='academics.syllabus', verbose_name='シラバスコード'),
        ),
    ]
