# Generated by Django 4.2.19 on 2025-03-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_syllabus_options_remove_lecture_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='terms',
        ),
    ]
