# Generated by Django 4.2.19 on 2025-03-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_syllabus_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='grade',
            field=models.IntegerField(blank=True, default=1, verbose_name='対象学年'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='instructor',
            field=models.CharField(blank=True, max_length=300, verbose_name='担当教員'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='name',
            field=models.CharField(max_length=300, verbose_name='講義名'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='講義の目的'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='type',
            field=models.CharField(blank=True, verbose_name='講義形態'),
        ),
    ]
