# Generated by Django 4.2.19 on 2025-03-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_lecture_is_public_editable_alter_lecture_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='is_public_editable',
            field=models.BooleanField(default=True),
        ),
    ]
