# Generated by Django 4.2.19 on 2025-03-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_lecture_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
    ]
