# Generated by Django 4.2.20 on 2025-03-26 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_picture'),
        ('academics', '0012_term_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='type',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='departments',
            field=models.ManyToManyField(related_name='syllabuses', to='accounts.department', verbose_name='履修可能学科'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
