# Generated by Django 4.2.20 on 2025-03-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_remove_syllabus_requirements_remove_syllabus_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='departments',
        ),
    ]
