# Generated by Django 4.2.20 on 2025-04-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_lecture_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
    ]
