# Generated by Django 4.2.20 on 2025-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_term_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attendance_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='出席回数'),
        ),
    ]
